name: Release Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Release:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Check out Repo
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Pack
      run: dotnet pack EasyDbMigrator\EasyDbMigrator\EasyDbMigrator.csproj -c Release
  
    - name: Publish to GitHub packages 
      run: dotnet nuget push EasyDbMigrator\EasyDbMigrator\Release\*.nupkg --api-key oy2fu6vok2pyhtskpl7abbsfeidoqdmuphxoudur5xxgja --source https://api.nuget.org/v3/index.json
