name: Buld Test and Release Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  BuildAndTest:
    name: build, test and codecoverage
    runs-on: ubuntu-latest
    timeout-minutes: 15
  
    steps:
    - name: Check out Repo
      uses: actions/checkout@v2

    - name: Setup .NET Core 6.0.x LTS
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
   
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build debug version
      run: dotnet build --configuration Debug --no-restore
    
    - name: Run unittest with code-coverage
      run: dotnet test --no-build --verbosity normal --filter Category!=Integrationtest /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    
    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v1

  Release:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [BuildAndTest]
    timeout-minutes: 10
    
    steps:
    - name: Check out Repo
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Package
      run: dotnet pack -c Release -o . EasyDbMigrator\EasyDbMigrator.csproj
    
    - name: Publish
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json

