name: Release Master NuGet

on:
  push:
    branches: [ master ]
 

jobs:
  Release:
    name: Release to Nuget
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Check out Repo
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Pack
      run: dotnet pack EasyDbMigrator\\EasyDbMigrator.csproj -c Release
  
    - name: Publish to GitHub packages 
      run: dotnet nuget push /home/runner/work/EasyDbMigrator/EasyDbMigrator/EasyDbMigrator/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

