name: Release Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Release:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Check out Repo
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Package
      run: dotnet pack -c Release -o . EasyDbMigrator\\EasyDbMigrator.csproj -Verbosity:detailed
    
    - name: Publish
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json -SkipDuplicate

