name: Build (Release version)

on:
  push:
    branches:
      - "**"
    branches-ignore:
      - master
    
jobs:
  BuildReleaseVersion:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Check out Repo
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Build Release
      run: dotnet build --configuration Release
    
    



